import type { Recipe, Folder } from "@/lib/db/schema";

export const DEMO_FOLDERS: Folder[] = [
  {
    id: "demo-f1",
    userId: "demo",
    name: "Weeknight Dinners",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "demo-f2",
    userId: "demo",
    name: "Sunday BBQ",
    createdAt: new Date("2024-01-02"),
  },
  {
    id: "demo-f3",
    userId: "demo",
    name: "Sweet Treats",
    createdAt: new Date("2024-01-03"),
  },
];

export const DEMO_RECIPES: Recipe[] = [
  {
    id: "demo-r1",
    userId: "demo",
    name: "Spaghetti Carbonara",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&q=80",
    dishTypes: ["dinner"],
    folderIds: ["demo-f1"],
    tags: ["pasta", "quick", "italian"],
    prepTime: 10,
    cookTime: 20,
    rating: 5,
    ingredients: [
      { amount: "400", unit: "g", name: "spaghetti" },
      { amount: "200", unit: "g", name: "pancetta" },
      { amount: "4", unit: "", name: "egg yolks" },
      { amount: "100", unit: "g", name: "pecorino romano" },
    ],
    instructions: "Boil pasta. Fry pancetta. Mix yolks with cheese. Combine off heat.",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "demo-r2",
    userId: "demo",
    name: "Grilled Ribeye Steak",
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80",
    dishTypes: ["dinner"],
    folderIds: ["demo-f2"],
    tags: ["beef", "steak", "protein"],
    prepTime: 5,
    cookTime: 15,
    rating: 5,
    ingredients: [
      { amount: "2", unit: "", name: "ribeye steaks" },
      { amount: "2", unit: "tbsp", name: "olive oil" },
      { amount: "1", unit: "tsp", name: "sea salt" },
      { amount: "1", unit: "tsp", name: "black pepper" },
    ],
    instructions: "Season steaks. Grill 4 min per side for medium-rare. Rest 5 min.",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "demo-r3",
    userId: "demo",
    name: "Chocolate Lava Cake",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80",
    dishTypes: ["snack"],
    folderIds: ["demo-f3"],
    tags: ["chocolate", "baking", "indulgent"],
    prepTime: 15,
    cookTime: 12,
    rating: 4,
    ingredients: [
      { amount: "200", unit: "g", name: "dark chocolate" },
      { amount: "100", unit: "g", name: "butter" },
      { amount: "4", unit: "", name: "eggs" },
      { amount: "60", unit: "g", name: "sugar" },
    ],
    instructions:
      "Melt chocolate and butter. Whisk eggs and sugar. Combine and bake at 220°C for 12 min.",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "demo-r4",
    userId: "demo",
    name: "Margherita Pizza",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80",
    dishTypes: ["lunch", "dinner"],
    folderIds: [],
    tags: ["italian", "vegetarian", "classic"],
    prepTime: 30,
    cookTime: 12,
    rating: 5,
    ingredients: [
      { amount: "250", unit: "g", name: "pizza dough" },
      { amount: "100", unit: "ml", name: "tomato sauce" },
      { amount: "150", unit: "g", name: "fresh mozzarella" },
      { amount: "10", unit: "", name: "basil leaves" },
    ],
    instructions:
      "Roll dough. Spread sauce. Add mozzarella. Bake at 250°C for 10-12 min. Top with basil.",
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "demo-r5",
    userId: "demo",
    name: "Chicken Tikka Masala",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80",
    dishTypes: ["dinner"],
    folderIds: ["demo-f1"],
    tags: ["chicken", "curry", "spicy"],
    prepTime: 20,
    cookTime: 40,
    rating: 4,
    ingredients: [
      { amount: "700", unit: "g", name: "chicken breast" },
      { amount: "400", unit: "ml", name: "coconut cream" },
      { amount: "2", unit: "tbsp", name: "tikka masala paste" },
      { amount: "1", unit: "", name: "onion" },
    ],
    instructions:
      "Marinate chicken. Brown onions. Add paste and chicken. Simmer with cream for 20 min.",
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "demo-r6",
    userId: "demo",
    name: "French Onion Soup",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80",
    dishTypes: ["lunch"],
    folderIds: [],
    tags: ["french", "comfort", "winter"],
    prepTime: 10,
    cookTime: 60,
    rating: 4,
    ingredients: [
      { amount: "6", unit: "", name: "large onions" },
      { amount: "1", unit: "L", name: "beef broth" },
      { amount: "200", unit: "g", name: "gruyère cheese" },
      { amount: "4", unit: "", name: "slices baguette" },
    ],
    instructions:
      "Caramelise onions 45 min. Add broth. Simmer 15 min. Top with bread and cheese, broil.",
    createdAt: new Date("2024-03-10"),
  },
];
