import type { Recipe, Folder } from "@/lib/db/schema";

export const DEMO_FOLDERS: Folder[] = [
  { id: "demo-f1", userId: "demo", name: "Weeknight Dinners", createdAt: new Date("2024-01-01") },
  { id: "demo-f2", userId: "demo", name: "Sunday BBQ", createdAt: new Date("2024-01-02") },
  { id: "demo-f3", userId: "demo", name: "Sweet Treats", createdAt: new Date("2024-01-03") },
];

export const DEMO_RECIPES: Recipe[] = [
  {
    id: "demo-r1",
    userId: "demo",
    name: "Spaghetti Carbonara",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=900&q=80",
    imageUrls: [],
    dishTypes: ["dinner"],
    folderIds: ["demo-f1"],
    tags: ["pasta", "quick", "italian"],
    prepTime: 10,
    cookTime: 20,
    rating: 5,
    description:
      "Silky Roman pasta built on egg yolks, pecorino and crisp pancetta — no cream, ever.",
    servings: 2,
    difficulty: "easy",
    cuisine: "Italian",
    calories: 640,
    source: "Family recipe",
    ingredients: [
      { amount: "400", unit: "g", name: "spaghetti" },
      { amount: "200", unit: "g", name: "pancetta" },
      { amount: "4", unit: "", name: "egg yolks" },
      { amount: "100", unit: "g", name: "pecorino romano" },
    ],
    instructions: "Boil pasta. Fry pancetta. Mix yolks with cheese. Combine off heat.",
    steps: [
      { text: "Bring a large pot of well-salted water to a boil and cook the spaghetti until al dente." },
      { text: "Meanwhile, fry the pancetta in a dry pan over medium heat until golden and crisp." },
      { text: "Whisk the egg yolks with the grated pecorino and plenty of black pepper." },
      { text: "Off the heat, toss the hot pasta with the pancetta, then the egg mixture, loosening with pasta water until glossy." },
    ],
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "demo-r2",
    userId: "demo",
    name: "Grilled Ribeye Steak",
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462?w=900&q=80",
    imageUrls: [],
    dishTypes: ["dinner"],
    folderIds: ["demo-f2"],
    tags: ["beef", "steak", "protein"],
    prepTime: 5,
    cookTime: 15,
    rating: 5,
    description:
      "A thick ribeye, salted hard and seared over fire for a deep crust and a rosy medium-rare centre.",
    servings: 2,
    difficulty: "medium",
    cuisine: "American",
    calories: 820,
    source: "Sunday BBQ",
    ingredients: [
      { amount: "2", unit: "", name: "ribeye steaks" },
      { amount: "2", unit: "tbsp", name: "olive oil" },
      { amount: "1", unit: "tsp", name: "sea salt" },
      { amount: "1", unit: "tsp", name: "black pepper" },
    ],
    instructions: "Season steaks. Grill 4 min per side for medium-rare. Rest 5 min.",
    steps: [
      { text: "Pat the steaks dry and season generously with salt and pepper. Let them come to room temperature." },
      { text: "Heat the grill to high and rub the steaks with olive oil." },
      { text: "Grill 4 minutes per side for medium-rare, turning once." },
      { text: "Rest for 5 minutes before slicing against the grain." },
    ],
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "demo-r3",
    userId: "demo",
    name: "Chocolate Lava Cake",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=900&q=80",
    imageUrls: [],
    dishTypes: ["snack"],
    folderIds: ["demo-f3"],
    tags: ["chocolate", "baking", "indulgent"],
    prepTime: 15,
    cookTime: 12,
    rating: 4,
    description:
      "Individual dark-chocolate cakes with a molten centre that spills out at the first spoonful.",
    servings: 4,
    difficulty: "medium",
    cuisine: "French",
    calories: 480,
    source: "Sweet Treats",
    ingredients: [
      { amount: "200", unit: "g", name: "dark chocolate" },
      { amount: "100", unit: "g", name: "butter" },
      { amount: "4", unit: "", name: "eggs" },
      { amount: "60", unit: "g", name: "sugar" },
    ],
    instructions:
      "Melt chocolate and butter. Whisk eggs and sugar. Combine and bake at 220°C for 12 min.",
    steps: [
      { text: "Melt the chocolate and butter together until smooth, then let cool slightly." },
      { text: "Whisk the eggs and sugar until pale and thick." },
      { text: "Fold the chocolate into the eggs, then divide between buttered ramekins." },
      { text: "Bake at 220°C for 12 minutes — the edges set, the centre stays molten. Turn out and serve at once." },
    ],
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "demo-r4",
    userId: "demo",
    name: "Margherita Pizza",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=900&q=80",
    imageUrls: [],
    dishTypes: ["lunch", "dinner"],
    folderIds: [],
    tags: ["italian", "vegetarian", "classic"],
    prepTime: 30,
    cookTime: 12,
    rating: 5,
    description:
      "The Neapolitan classic: blistered dough, San Marzano tomato, fresh mozzarella and basil.",
    servings: 2,
    difficulty: "medium",
    cuisine: "Italian",
    calories: 710,
    source: "Family recipe",
    ingredients: [
      { amount: "250", unit: "g", name: "pizza dough" },
      { amount: "100", unit: "ml", name: "tomato sauce" },
      { amount: "150", unit: "g", name: "fresh mozzarella" },
      { amount: "10", unit: "", name: "basil leaves" },
    ],
    instructions:
      "Roll dough. Spread sauce. Add mozzarella. Bake at 250°C for 10-12 min. Top with basil.",
    steps: [
      { text: "Stretch the dough by hand into a round, leaving a thick rim." },
      { text: "Spread a thin layer of tomato sauce, leaving the edge bare." },
      { text: "Tear over the mozzarella. Bake at 250°C for 10–12 minutes until the crust is charred and blistered." },
      { text: "Finish with fresh basil and a drizzle of olive oil." },
    ],
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "demo-r5",
    userId: "demo",
    name: "Chicken Tikka Masala",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=900&q=80",
    imageUrls: [],
    dishTypes: ["dinner"],
    folderIds: ["demo-f1"],
    tags: ["chicken", "curry", "spicy"],
    prepTime: 20,
    cookTime: 40,
    rating: 4,
    description:
      "Charred marinated chicken simmered in a spiced, creamy tomato gravy. A takeaway favourite, made better at home.",
    servings: 4,
    difficulty: "medium",
    cuisine: "Indian",
    calories: 560,
    source: "Weeknight Dinners",
    ingredients: [
      { amount: "700", unit: "g", name: "chicken breast" },
      { amount: "400", unit: "ml", name: "coconut cream" },
      { amount: "2", unit: "tbsp", name: "tikka masala paste" },
      { amount: "1", unit: "", name: "onion" },
    ],
    instructions:
      "Marinate chicken. Brown onions. Add paste and chicken. Simmer with cream for 20 min.",
    steps: [
      { text: "Marinate the diced chicken in half the paste for at least 20 minutes, then char in a hot pan." },
      { text: "Soften the sliced onion until golden." },
      { text: "Add the remaining paste and the chicken, stir to coat." },
      { text: "Pour in the coconut cream and simmer gently for 20 minutes until thick. Serve with rice." },
    ],
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "demo-r6",
    userId: "demo",
    name: "French Onion Soup",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=900&q=80",
    imageUrls: [],
    dishTypes: ["lunch"],
    folderIds: [],
    tags: ["french", "comfort", "winter"],
    prepTime: 10,
    cookTime: 60,
    rating: 4,
    description:
      "Deeply caramelised onions in rich beef broth, crowned with toasted baguette and bubbling Gruyère.",
    servings: 4,
    difficulty: "easy",
    cuisine: "French",
    calories: 390,
    source: "Winter comfort",
    ingredients: [
      { amount: "6", unit: "", name: "large onions" },
      { amount: "1", unit: "L", name: "beef broth" },
      { amount: "200", unit: "g", name: "gruyère cheese" },
      { amount: "4", unit: "", name: "slices baguette" },
    ],
    instructions:
      "Caramelise onions 45 min. Add broth. Simmer 15 min. Top with bread and cheese, broil.",
    steps: [
      { text: "Slice the onions thin and caramelise slowly in butter for about 45 minutes until deep brown." },
      { text: "Add the beef broth and simmer for 15 minutes." },
      { text: "Ladle into bowls, top each with toasted baguette and a thick layer of Gruyère." },
      { text: "Broil until the cheese is molten and bubbling." },
    ],
    createdAt: new Date("2024-03-10"),
  },
  {
    // A deliberately SPARSE recipe: this is what an existing recipe looks like
    // after migration — none of the new fields are filled. The card and recipe
    // page still render cleanly; missing fields simply collapse.
    id: "demo-r7",
    userId: "demo",
    name: "Leftover Veggie Bowl",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=900&q=80",
    imageUrls: [],
    dishTypes: ["lunch"],
    folderIds: [],
    tags: ["quick", "vegetarian"],
    prepTime: 5,
    cookTime: 10,
    rating: 4,
    description: "",
    servings: null,
    difficulty: null,
    cuisine: "",
    calories: null,
    source: "",
    ingredients: [
      { amount: "1", unit: "", name: "leftover roast vegetables" },
      { amount: "1", unit: "cup", name: "cooked rice" },
      { amount: "1", unit: "tbsp", name: "soy sauce" },
    ],
    instructions: "Warm the rice and vegetables in a hot pan. Splash with soy sauce, toss, and serve.",
    steps: [],
    createdAt: new Date("2024-03-12"),
  },
];
